<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Qu'est-ce-qu'un-Jupyter-notebook-?" data-toc-modified-id="Qu'est-ce-qu'un-Jupyter-notebook-?-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Qu'est-ce qu'un Jupyter notebook ?</a></span></li><li><span><a href="#Qu'est-ce-que-Julia-?" data-toc-modified-id="Qu'est-ce-que-Julia-?-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Qu'est-ce que Julia ?</a></span></li><li><span><a href="#Qu'est-ce-que-JuMP-?" data-toc-modified-id="Qu'est-ce-que-JuMP-?-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Qu'est-ce que JuMP ?</a></span><ul class="toc-item"><li><span><a href="#Mise-en-place" data-toc-modified-id="Mise-en-place-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Mise en place</a></span></li></ul></li><li><span><a href="#Construction-d'un-premier-problème-linéaire" data-toc-modified-id="Construction-d'un-premier-problème-linéaire-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Construction d'un premier problème linéaire</a></span><ul class="toc-item"><li><span><a href="#Un-second-problème-linéaire" data-toc-modified-id="Un-second-problème-linéaire-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Un second problème linéaire</a></span></li><li><span><a href="#Un-problème-non-linéaire" data-toc-modified-id="Un-problème-non-linéaire-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Un problème non-linéaire</a></span></li></ul></li></ul></div>

# Une prise en main rapide de Jupyter / Julia / JuMP

## Qu'est-ce qu'un Jupyter notebook ?

Un Jupyter notebook est un document qui contient 
+ du texte 
  - que l'on peut formatter à l'aide de Markdown
  - qui peut contenir des maths à l'aide de $\LaTeX$
+ du code
  - avec lequel on peut intéragir en ligne
  
Un notebook est une succession de cellule, chacune pouvant être soit du code, soit du texte.
Quelques astuces :
+ double-clicker pour voir le contenu et modifier une cellule
+ M / Y pour changer le type de cellule
+ Ctrl-enter pour éxecuter la cellule
+ shift-enter pour éxecuter la cellule et passer à la suivante
+ Alt-enter pour éxecuter la cellule et en ajouter une nouvelle

Vous pouvez télécharger le fichier .ipynb via l'onglet "file" en haut à gauche. Vous pouvez aussi télécharger un pdf.

## Qu'est-ce que Julia ?

Julia est un langage de programmation, comparable à Python. C'est un langage récent, développé pour le calcul scientifique. 

Quelques éléments intéressant :
+ langage open-source
+ langage compilé "Just-in-time"
+ langage disposant d'un terminal (comme python)
+ ...

Faisons nos premiers pas avec Julia. Exécuter les cellules suivantes (shift-enter), n'hésitez pas à modifier pour prendre en main :

In [34]:
1+1

2

In [35]:
a = [0 5 10 15]
a[1]

0

In [36]:
sum(a)

30

In [37]:
sum(x^2 for x in a)

350

In [38]:
length(a)

4

In [39]:
exp.(a) .- a #to apply an operation or function componentwise just add .  

1×4 Matrix{Float64}:
 1.0  143.413  22016.5  3.269e6

In [40]:
@doc exp # to get documentation on a function

```
exp(x)
```

Compute the natural base exponential of `x`, in other words $ℯ^x$.

See also [`exp2`](@ref), [`exp10`](@ref) and [`cis`](@ref).

# Examples

```jldoctest
julia> exp(1.0)
2.718281828459045

julia> exp(im * pi) == cis(pi)
true
```

```
exp(A::AbstractMatrix)
```

Compute the matrix exponential of `A`, defined by

$$
e^A = \sum_{n=0}^{\infty} \frac{A^n}{n!}.
$$

For symmetric or Hermitian `A`, an eigendecomposition ([`eigen`](@ref)) is used, otherwise the scaling and squaring algorithm (see [^H05]) is chosen.

[^H05]: Nicholas J. Higham, "The squaring and scaling method for the matrix exponential revisited", SIAM Journal on Matrix Analysis and Applications, 26(4), 2005, 1179-1193. [doi:10.1137/090768539](https://doi.org/10.1137/090768539)

# Examples

```jldoctest
julia> A = Matrix(1.0I, 2, 2)
2×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0

julia> exp(A)
2×2 Matrix{Float64}:
 2.71828  0.0
 0.0      2.71828
```


In [41]:
for i = 1:5
    println("itération ",i)
end

itération 1
itération 2
itération 3
itération 4
itération 5


In [42]:
function factorielle(n)
    if n == 0
        return 1
    end
    res = 1
    for i=1:n
        res = res * i
    end
    return res
end

factorielle (generic function with 1 method)

In [43]:
factorielle(5)

120

In [44]:
round(1.9453;sigdigits=2)

1.9

In [45]:
rand(3)

3-element Vector{Float64}:
 0.9948378958447538
 0.47880258058121783
 0.6075806321198127

Further info can be found [here](https://learnxinyminutes.com/docs/julia/) or in the [documentation](https://docs.julialang.org/en/v1/)



## Qu'est-ce que JuMP ?

JuMP est l'un des packages phare de Julia.

Il s'agit d'un package de modélisation, qui permet d'écrire un problème d'optimisation de manière simple puis de demander à un Solver de le résoudre.

Nous allons maintenant faire nos premiers pas avec JuMP.

Plus d'information sur http://www.juliaopt.org/JuMP.jl/v0.20.0/quickstart/ 

### Mise en place

Avant toute chose il faut installer puis appeler les bibliothèques utiles. 


In [46]:
import Pkg
#= 
Cette cellule peu prendre du temps à s'executer.
Pkg.add("GLPK")
Pkg.add("Ipopt")
Pkg.add("JuMP")
=#

On peut faire la liste des packages installés et leur version en executant la commande suivante.

In [47]:
Pkg.status()

      Status `C:\Users\maten\.julia\environments\v1.7\Project.toml`
  [a93c6f00] DataFrames v1.3.3
  [60bf3e95] GLPK v1.0.1
  [7073ff75] IJulia v1.23.3
  [b6b21f68] Ipopt v1.0.2
  [4076af6c] JuMP v1.0.0


Nous allons maintenant dire que nous souhaitons utiliser ces packages (comparable à "from packet import *" en python) 

[Cette commande peut prendre du temps]

In [48]:
using GLPK 
using Ipopt
using JuMP
# cette cellule peut prendre du temps à s'éxécuter.


## Construction d'un premier problème linéaire

Nous souhaitons résoudre le problème linéaire suivant
$$ \begin{align*} 
\min_{x,y} \quad & 2x+3y \\
s.c. \quad & x+y \geq 1 \\
& x \geq 0, y\geq 0 \\
\end{align*}$$

Commençons par construire le problème

In [49]:
OPTIMIZER = GLPK.Optimizer              # On définit un optimizer
m = Model(OPTIMIZER)       # On construit un problème d'optimisation

@variable(m,x>=0)                       # x est une variable réelle positive de m
@variable(m,y>=0)                       # y est une variable réelle positive de m

### Remarque les fonctions @variable / @objective / @constraint sont des fonctions spécifiques (des macros) 
# qui autorise de donner un argument comme 2*x+3*y sans qu'il soit évalué. 
# Ce n'est pas un comportement générique des fonctions julia.

@objective(m,Min, 2*x+3*y)              # l'objectif de m est de Minimiser 2*x+3*y

@constraint(m,x+y >= 1 )                # m a pour contrainte x+y <=1

x + y >= 1.0

On peut vérifier que m est bien ce que l'on souhaite

In [50]:
print(m)

On peut également résoudre m

In [51]:
optimize!(m)
println(termination_status(m))
println(primal_status(m))
println(dual_status(m))

OPTIMAL
FEASIBLE_POINT
FEASIBLE_POINT


Et si on souhaite connaître la valeur optimale du problème ou des solutions optimales on peut les avoir de la manière suivante

In [52]:
println(JuMP.objective_value(m))
println("x = ",JuMP.value(x))
println("y = ",JuMP.value(y))

2.0
x = 1.0
y = 0.0


### Un second problème linéaire

Nous allons maintenant construire un problème linéaire plus complexe.
$$
\begin{align*}
\min_{x\in R^n} \quad & \sum_{i=1}^n c_i x_i \\
s.c. \quad & \sum_{i=1}^n x_i \geq n \\
&  -1 \leq x_i \leq 2 & \forall i
\end{align*}
$$

In [53]:
m2 = Model(OPTIMIZER)
n = 10                                    # on choisit n = 10, mais vous pouvez le modifier
c = rand(n)                               # c est choisi ici de manière aléatoire                                              

@variable(m2, -1<= x[1:n] <= 2)           # x est une variable de m2 contenant n éléments x[1], x[2],...,x[n] tous compris entre -1 et 2

@objective(m2,Min, sum(c[i]*x[i] for i=1:n) )

@constraint(m2,sum(x[i] for i=1:n) >= n)
                        
print(m2)            

In [54]:
optimize!(m2)
println(termination_status(m2))

OPTIMAL


In [55]:
value.(x)

10-element Vector{Float64}:
 -1.0
  2.0
 -1.0
  2.0
 -1.0
  1.0
  2.0
  2.0
  2.0
  2.0

Ajoutons maintenant une série de contraintes de la forme
$$ x_i + x_{i+1} \leq 1, \qquad \forall i \in 2, \dots, n-1$$

In [59]:
for i = 1 : n-1
    @constraint(m2, x[i]+x[i+1] <= 1)
end

In [61]:
optimize!(m2)
println(termination_status(m2))
value.(x)

INFEASIBLE


10-element Vector{Float64}:
  3.0
 -2.0
  3.0
  2.0
  0.0
  1.0
  0.0
  2.0
 -1.0
  2.0

### Un problème non-linéaire

Nous allons terminer avec un problème non-linéaire simple.

$$
\begin{align*}
\min_{x \in R^{n.m}} \quad & \sum_{i,j} x_{i,j}^2 \\
s.c. \quad & \sum_{i=1}^n x_{i,j} = 1 & \forall j \in [m] 
\end{align*}
$$

In [62]:
using Ipopt # Solveur de problèmes non-linéaires par point intérieur.

In [63]:
OPTIMIZER_NL = Ipopt.Optimizer

m3 = Model(OPTIMIZER_NL)

N,M = 5,7 

@variable(m3, x[i=1:N, j=1:M])

@objective(m3, Min, sum(x[i,j]^2 for i=1:N, j=1:M))

for j=1:M
    @constraint(m3, sum(x[i,j] for i =1:N)==1)
end

@constraint(m3, x[1,1]^2+x[1,2]^2 <= 0.5) # we can add quadratic constraints

@NLconstraint(m3, x[2,1]^2 + x[2,2]^3 <= 1) # we can add non-linear constraints

(x[2,1] ^ 2.0 + x[2,2] ^ 3.0) - 1.0 <= 0

In [64]:
print(m3)

In [65]:
optimize!(m3)
println(objective_value(m3))


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

This is Ipopt version 3.14.4, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:       35
Number of nonzeros in inequality constraint Jacobian.:        4
Number of nonzeros in Lagrangian Hessian.............:       39

Total number of variables............................:       35
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        7
Total number of inequality co

In [66]:
value.(x)

5×7 Matrix{Float64}:
 0.2  0.2  0.2  0.2  0.2  0.2  0.2
 0.2  0.2  0.2  0.2  0.2  0.2  0.2
 0.2  0.2  0.2  0.2  0.2  0.2  0.2
 0.2  0.2  0.2  0.2  0.2  0.2  0.2
 0.2  0.2  0.2  0.2  0.2  0.2  0.2

Tested Version :
- JuMP 0.20 / Julia 1.5.2